import { LedgerEntry, Opportunity, UserProfile } from "./types";
import { scoreOpportunities } from "./engine";

export const defaultProfile: UserProfile = {
  name: "Alex",
  skills: ["TypeScript", "Python", "React", "Figma"],
  interests: ["AI", "developer tools", "education", "community"],
  careerStage: "Student / early career",
  goals: "Build an AI education product, meet thoughtful collaborators, and find technical opportunities.",
  location: "Chicago, Illinois",
  latitude: 41.8781,
  longitude: -87.6298,
  travelRadius: 12,
  formatPreference: "both",
  availability: "evenings",
  weights: { relevance: 38, distance: 20, format: 14, timing: 13, caliber: 15 },
};

export const demoEvents: Opportunity[] = [
  {
    id: "chi-ai-build-night",
    title: "Chicago AI Build Night",
    source: "ML Collective Chicago",
    sourceType: "demo",
    url: "https://www.meetup.com/",
    description: "A hands-on evening for builders shipping practical AI projects. Bring a laptop, find collaborators, and get feedback from local founders and ML engineers.",
    startsAt: "2026-07-23T18:30:00-05:00",
    endsAt: "2026-07-23T21:30:00-05:00",
    format: "in-person",
    venue: "mHUB",
    address: "1623 W Fulton St, Chicago",
    distanceMiles: 3.2,
    latitude: 41.8866,
    longitude: -87.6686,
    category: "Build session",
    tags: ["AI", "hands-on", "founders", "developer tools"],
    caliberReason: "Focused organizer network and a hands-on project format.",
    friendNames: ["Maya Chen", "Jordan Bell"],
  },
  {
    id: "open-source-edu",
    title: "Open Source for Education Sprint",
    source: "Code for Chicago",
    sourceType: "demo",
    url: "https://www.codeforamerica.org/",
    description: "A Saturday contribution sprint for civic and education technology projects. First-time contributors are paired with maintainers and product mentors.",
    startsAt: "2026-07-25T10:00:00-05:00",
    endsAt: "2026-07-25T16:00:00-05:00",
    format: "hybrid",
    venue: "1871 Chicago",
    address: "222 W Merchandise Mart Plaza, Chicago",
    distanceMiles: 1.4,
    latitude: 41.8882,
    longitude: -87.6351,
    category: "Workshop",
    tags: ["education", "open source", "Python", "mentorship"],
    caliberReason: "Named project maintainers and structured mentorship.",
    friendNames: ["Maya Chen"],
  },
  {
    id: "openai-build-week",
    title: "Build Week: Education Challenge",
    source: "OpenAI Community",
    sourceType: "demo",
    url: "https://openai.com/",
    description: "A remote building week for people creating useful education experiences with AI. Teams receive an idea review, office hours, and a public demo day.",
    startsAt: "2026-07-28T09:00:00-05:00",
    endsAt: "2026-08-03T18:00:00-05:00",
    format: "online",
    category: "Hackathon",
    tags: ["AI", "education", "hackathon", "React"],
    caliberReason: "Competitive build format with office hours and public demos.",
    friendNames: ["Jordan Bell", "Priya Shah", "Noah Kim"],
  },
  {
    id: "product-design-salon",
    title: "Product Design Salon: Learning Loops",
    source: "Designation",
    sourceType: "demo",
    url: "https://www.eventbrite.com/",
    description: "A conversation on research, learner motivation, and the small interactions that help people make progress. Includes lightning talks and networking.",
    startsAt: "2026-07-30T18:00:00-05:00",
    format: "in-person",
    venue: "Fulton Market",
    distanceMiles: 3.7,
    category: "Talk",
    tags: ["Figma", "education", "product", "networking"],
    caliberReason: "Curated speakers from education product teams.",
  },
  {
    id: "web3-fundraiser",
    title: "Web3 Fundraising Masterclass",
    source: "Venture Circle",
    sourceType: "demo",
    url: "https://www.eventbrite.com/",
    description: "An introductory fundraising panel for early crypto startups, followed by investor networking.",
    startsAt: "2026-07-24T12:00:00-05:00",
    format: "online",
    category: "Talk",
    tags: ["web3", "fundraising", "startups"],
    caliberReason: "Small panel format with local investors.",
  },
  {
    id: "north-shore-sales",
    title: "North Shore Sales Leaders Breakfast",
    source: "Chamber Calendar",
    sourceType: "demo",
    url: "https://www.eventbrite.com/",
    description: "Monthly breakfast networking for enterprise sales leaders and account executives.",
    startsAt: "2026-07-29T07:30:00-05:00",
    format: "in-person",
    venue: "Evanston",
    distanceMiles: 17.8,
    category: "Networking",
    tags: ["sales", "enterprise", "networking"],
    caliberReason: "Local professional association event.",
  },
  {
    id: "demo-day-duplicate",
    title: "AI Education Demo Day",
    source: "University Tech Calendar",
    sourceType: "demo",
    url: "https://www.eventbrite.com/",
    description: "Student teams present learning tools and receive feedback from educators and engineers.",
    startsAt: "2026-08-01T17:00:00-05:00",
    format: "in-person",
    venue: "UIC Innovation Center",
    distanceMiles: 4.9,
    category: "Demo day",
    tags: ["AI", "education", "students"],
    caliberReason: "University showcase with evaluator feedback.",
  },
];

export const makeDemoEvents = (profile = defaultProfile) => scoreOpportunities(demoEvents, profile);

export const initialLedger: LedgerEntry[] = [
  { id: "l1", kind: "source", status: "complete", title: "Eventbrite connector", detail: "6 events normalized from the configured search.", at: "Just now", duration: "0.8s" },
  { id: "l2", kind: "source", status: "complete", title: "University tech calendar", detail: "4 structured events read from the calendar feed.", at: "Just now", duration: "0.4s" },
  { id: "l3", kind: "source", status: "complete", title: "Community RSS feed", detail: "5 events parsed without an LLM call.", at: "Just now", duration: "0.3s" },
  { id: "l4", kind: "source", status: "skipped", title: "Web discovery", detail: "Disabled in sample mode. Connect Exa and enable compliant open-web discovery to search public event pages.", at: "Just now" },
  { id: "l5", kind: "dedup", status: "complete", title: "Deduplication pass", detail: "1 duplicate merged: 94% title match, same date, 0.3 mi apart.", at: "Just now", duration: "0.02s" },
  { id: "l6", kind: "score", status: "complete", title: "Ranked your opportunity feed", detail: "7 scores calculated; 4 deterministic factors + cached caliber signal.", at: "Just now", duration: "0.07s" },
];
